version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:21"
      timezone: "Europe/Budapest"

    open-pull-requests-limit: 5

    groups:
      routine-python-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:21"
      timezone: "Europe/Budapest"

    groups:
      routine-action-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:51"
      timezone: "Europe/Budapest"

    open-pull-requests-limit: 5
