patterns:
  yyyy_mm_dd: '^\d{4}-\d{2}-\d{2}$'
  yyyy_mm_dd_slash: '^\d{4}/\d{2}/\d{2}$'
  mon_dd_yyyy: '^[A-Za-z]{3,9}\s+\d{1,2},\s*\d{4}$'
  dd_mon_yyyy: '^\d{1,2}-[A-Za-z]{3,9}-\d{4}$'
  yyyy_mm: '^\d{4}-\d{2}$'
  yyyy_mm_slash: '^\d{4}/\d{2}$'
  mm_yyyy: '^\d{2}-\d{4}$'
  mm_yyyy_slash: '^\d{2}/\d{4}$'
  mon_yyyy: '^[A-Za-z]{3,9}\s+\d{4}$'
  yyyy: '^\d{4}$'
  dd_mm_yyyy_slash: '^\d{1,2}/\d{1,2}/\d{4}$'
  dd_mm_yyyy_dash: '^\d{1,2}-\d{1,2}-\d{4}$'

  time_strip: 'T.*$'

  # Interval pattern
  # Separator is restricted to '/' or ' to ' or ' - ' (with spaces)
  interval: '^(?P<start>\d{4}(?:[-/A-Za-z]\w*)?(?:[-/\s]\d{1,2})?)\s*(?:/|to| - )\s*(?P<end>\d{4}(?:[-/A-Za-z]\w*)?(?:[-/\s]\d{1,2})?)$'

sampling_keywords:
  - "collection_date"
  - "collection date"
  - "extraction_date"
  - "time of isolation"
  - "Isolation_date"
  - "year of collection"
  - "collection data"

other_date_keywords:
  - "ena_submission_tool"
  - "ena_last_update"
  - "ena last update"
  - "ena_first_public"
  - "last_update"
  - "last update"
  - "last-modified"
  - "first public"
  - "insdc_first_public"
  - "insdc_last_update"
  - "submission_date"
  - "_submission_date"
  - "Recieved_date"
  - "receipt date"
  - "ngdc_release_date"
  - "Sequencing date"
  - "kobic_registration_date"
  - "kobic_release_date"
  - "kobic_submission_date"
  - "UploadDate"
  - "date_sequencing"
  - "DNA_extraction_date"
  - "date_for_experiment_in_lc"
  - "cult_isol_date"
  - "admission_date"

null_values:
  - "na"
  - "n/a"
  - "missing"
  - "not_applicable"
  - "not collected"
  - "not known"
  - "unknown"
  - "null"
  - "none"
  - "not provided"
  - "not available"
  - "not determined"
  - "restricted_access"
  - "missing: third party data"
  - "SRA-Webin"
  - "-"

# Attribute names that should be explicitly ignored.
blacklist:
  - "serovar"
  - "isolation_source"
  - "collected_by"
  - "collected by"
  - "strain"
  - "submitter_id"
  - "isolate"
  - "host_age"
  - "culture_collection"
  - "supplier_name"
  - "passage_date"
  - "sample_name"
  - "amrfinderplus_db_version"
  - "food_quality_date"
  - "subject id"
  - "anonymized name"
  - "pubmed_id-0"
  - "pubmed_id-1"
  - "sample_type"
  - "cgMLST Complex type (www.cgmlst.org/ncs)"
  - "alternate_ID"
  - "petition_id"
  - "genotype"
  - "label"
  - "assembly_date"
  - "estimated_size"
  - "ID"
  - "host subject id"
  - "isol_growth_condt"
  - "Sequence_type"
  - "MLST"
  - "MLST Type"
  - "geographic location (latitude)"
  - "geographic location (longitude)"
  - "ArrayExpress-STRAIN_OR_LINE"
  - "isolate_name_alias"
  - "library_id"
  - "filename"
  - "filename2"
  - "isolate-name-alias"
  - "MLST#_Scheme"
  - "host_taxid"
  - "ref_biomaterial"
  - "total_length"
  - "library_ID"
  - "alias"
  - "carb_dioxide"
  - "altitude"
  - "common name"
  - "host_spec_range"
  - "BI GSSR Sample ID"
  - "pmid"
  - "tax_id"
  - "num_replicons"
  - "pubmed_id"
  - "swab_id"
  - "clonal complex"
  - "alt_id"
  - "ArrayExpress-StrainOrLine"
  - "host_disease_stage"
  - "FDA_Lab_Id"
  - "host_description"
  - "lesion_size_mm2"
  - "MLST#_Schema"
  - "Sample Number"
  - "ST (Multi Locus Sequene Type - what follows to the right are individual allele calls in the  7 gene typing scheme"
  - "host scientific name"
  - "readfile_1"
  - "readfile_2"
  - "pirnay_name"
  - "env_local_scale"
  - "depth"
  - "Calcium"
  - "Magnesium"
  - "seqID"
  - "UoS_isolate_ID"
  - "Sequencing_ID"
  - "ST"
  - "7-allele ST"
  - "Outbreak"
  - "Warwick ST"
  - "strain_original"
  - "sequence type (warwick scheme)"
  - "Key"
  - "similar_to"
  - "Sequence Type (Achtman MLST)"
  - "Sodium"
  - "Lab_ID"
  - "host_age [months]"
  - "fumc"
  - "MLST2"
  - "serotype"
  - "icd"
  - "Title"
  - "strain background"
  - "SPUID"
  - "MLST Type Pasteur"
  - "source_name"
  - "strain/background"
  - "internal_id"
  - "MLST Type Oxfort"
  - "samp_size"
  - "contig N50"
  - "Container_label"
  - "antibody"
  - "taxonomy id"
  - "cgMLST"
  - "Date of Death in Years (range)"
  - "source_material_id"
  - "specimen_voucher"
  - "other_strain_names"
  - "MIC Value"
  - "elev"
  - "experimental batch"
  - "batch"
  - "CRKP_Sputum1"
  - "last_updated_by"
  - "Annotation Date"
  - "collection date (old)"
  - "assembly_date"
  - "biomaterial_provider"
  - "Harvest Year"
  - "'collection_date'"
