# Keywords to identify host-related attributes
keywords:
  - "host"
  - "host_taxid"

# Attributes to ignore
blacklist:
  - "host_subject_id"
  - "host_disease"
  - "host health state"
  - "host_age"
  - "is the sequenced pathogen host associated?"
  - "host_sex"
  - "host status"
  - "host associated"
  - "host_disease_stage"
  - "host_age [months]"
  - "host_variety"
  - "isolation source non-host-associated"
  - "host family relationship"
  - "isolation source host-associated"
  - "host_tissue_sampled"
  - "isolation source host associated"
  - "host_body_mass_index"
  - "Host gender"
  - "host_genotype"
  - "host_spec_range"
  - "host_disease_outcome"
  - "host-associated environmental package"
  - "host_disease_stat"
  - "host_infra_specific_rank"
  - "host_life_stage"
  - "'host_disease'"
  - "host_diet"
  - "host_height"
  - "host_occupation"
  - "Host health"
  - "host_animal_breed"
  - "host_phenotype"
  - "host_body_habitat"
  - "host_description"
  - "host_body_product"
  - "lab_host"
  - "attribute_package"
  - "Host_Litter"
  - "host_group_size"
  - "host_housing"
  - "hosts_age"
  - "Experiment host strain"
  - "host_dev_stage"
  - "host_infra_specific_name"
  - "host_info"
  - "host's age in days"
  - "host_disease_status"
  - "host_strain"
  - "Health status of host"
  - "host_growth_cond"
  - "host_stage"
  - "host_length"
  - "host_tot_mass"
  - "host_sample"
  - "host_common_name" # Seems to be always present in addition to the regular host attribute, so likely does not improve the accuracy of the results.
  - "host_dependence"
  - "host_note"
  - "host_lab."
  - "dhost_isease_stage"
  - "host_color"
  - "host_number"
  - "host_body_temp"
  - "host_or_sample_description"
  - "host_age_range"
  - "Host NPGS accession"

# Values that should be treated as missing or null
null_values:
  - "missing"
  - "mising"
  - "not collected"
  - "Not collecte"
  - "no collected"
  - "no collect"
  - "not colllected"
  - "not determined"
  - "not available"
  - "not available: not collected"
  - "not applicable"
  - "no applicable"
  - "non-applicable"
  - "not applicaple"
  - "not aplicable"
  - "not applocable"
  - "not apply"
  - "not applicable1"
  - "not applicable2"
  - "not applicable3"
  - "not applicable5"
  - "not applicapble"
  - "['', 'not applicable']"
  - "Not Applicable [GENEPIO:0001619]"
  - "Not appropriate"
  - ""
  - "Not applied"
  - "not provided"
  - "not known"
  - "forgeted"
  - "unknown"
  - "undetermined"
  - "/"
  - "na"
  - "nan"
  - "n/a"
  - "N.A"
  - "n. a."
  - "N.A."
  - "null"
  - "none"
  - "No host"
  - "reference"
  - "unidentified"
  - "host"
  - "Parent"
  - "Escherichia"
  - "Escherichia coli"
  - "E.coli"
  - "E. coli"
  - "E coli"
  - "Escherichia coli (blaTEM)" # gene
  - "-"
  - "Isolate"
  - "ddss"
  - "ND"
  - "Microbiology"
  - "Acinetobacter baumannii"
  - "Klebsiella pneumoniae"
  - "Enterococcus faecium"
  - "Pseudomonas"
  - "Pseudomonas aeruginosa"
  - "Staphylococcus"
  - "Acinetobacter"
  - "genus"
  - "MRSA"
  - "firmicutes"
  - "208964" # taxid
  - "32644" # unclassified sequence taxid
  - "llan" # researcher's name? (SAMN14775763)
  - "xiangbin liu"
  - "micribial"
  - "microbial"
  - "missinng"
  - "misssing"
  - "missing: lab stock"
  - "missing: lab strain"
  - "restricted access"
  - "H"
  - "bacteria"
  - "Becteria"
  - "Bacterial"
  - "Bacteroidetes"
  - "bacteroid"
  - "Salmonella enterica"
  - "2" # bacterial taxid
  - "187" # b-proteobacteria taxid
  - "1758" # non-existing taxid
  - "1"
  - "unknow"
  - "Non Animal"
  - "male"
  - "female"
  - "M"
  - "F"
  - "germ"
  - "SCELSE"
  - "fgr"
  - "HUMAN/FOOD"
  - "natural / free-living"
  - "Food/Environment"
  - "lampine" # ?
  - "RL3018"
  - "RL3019"
  - "warm-blooded organisms" # TODO: not monophyletic. Might assign multiple taxons in the future for groups like this
  - "Bovine, juvenilehomo sapiens" # SAMEA3529394
  - "opportunistic pathogen"
  - "Planktonicevolution"
  - "Beadevolution"
  - "In vitro"
  - "invitro"
  - "mg1655"
  - "MG1655_lacZ::Lpl_rpoD"
  - "BW25113"
  - "k12/MG1665"
  - "BL21"
  - "RCRC 4210"
  - "CF-003" # PRJNA800578
  - "CF-004"
  - "CF-006"
  - "CF-008"
  - "CF-009"
  - "CF-010"
  - "CF-011"
  - "CF-017"
  - "CF-018"
  - "CF-019"
  - "CF-021"
  - "Culture"
  - "CCL-185"
  - "DSM_1103"
  - "self"
  - "labhost"
  - "artificial"
  - "laboratory"
  - "laboratory"
  - "laboratroy"
  - "lab"
  - "lab strain"
  - "laboratory derived"
  - "not applicable: laboratory strain"
  - "laboratory strain"
  - "labaratory strain"
  - "BL21"
  - "BW25113"
  - "mg1655"
  - "MG1655_lacZ::Lpl_rpoD"
  - "k12/MG1665"
  - "RCRC 4210" # SAMN25166293
  - "In vitro"
  - "invitro"
  - "Culture"
  - "DSM_1103"
  - "Synthetic"
  - "artificial"
  - "M9 liquid Media"
  - "Enterobacter cloacae"
  - "Escherichia coli WM3064"
  - "Escherichia coli str. K-12 substr. BW25113"
  - "Escherichia coli KRX"
  - "Escherichia coli K-12"
  - "Escherichia coli K12"
  - "Escherichia coli JM109"
  - "Standard strains"
  - "Laboratory E. coli strain"
  - "Escherichia coli MG1655"
  - "Escherichia coli MG1655 DeltaLon"
  - "Escherichia coli str.K-12 substr. MG1655 strain"
  - "ATCC"
  - "e coli strain"
  - "NIST Mixed Microbial RM strain"
  - "ZymoBIOMICS Microbial Community Standard Strain"
  - "E. coli K 12"
  - "Escherichia coli TG1"
  - "laboratory strain mutant"
  - "Escherichia phage T7"
  - "E. coli strain C600"
  - "laboratory strain (not applicable)"
  - "E coli MTCC730"
  - "Saccharomyces cerevisiae"
  - "E. coli TRP"
  - "TRP"
  - "Escherichia coli EC100"
  - "Model bacteria E. coli C60"
  - "Escherichia coli DH5"
  - "Escherichia coli BW27783"
  - "E. coli ECONIH5"
  - "Escherichia coli (blaCTX)"
  - "Vibrio natriegens"
  - "Rhodospirillum rubrum"
  - "Escherichia coli A178"
  - "vaccine strain"
  - "Escherichia coli dh10b"
  - "['Bacteria', '']"
  - "Escherichia coli DH5a"
  - "Rhodococcus M4"
  - "laboratory isolate"
  - "Pure culture"
  - "laboratory host"
  - "DSMZ strain"
  - "Anopheles gambiae G3 strain, lab colony"
  - "E. Coli - MG1655 rph+"
  - "Pseudomonas aeruginosa PA3"
  - "Pseudomonas aeruginosa MPAO1"
  - "Pseudomonas aeruginosa PAO1"
  - "Lab strain, not applicable"
  - "Pseudomonas sp."
  - "aeruginosa"
  - "Staphylococcus aureus SH1000 pKikume"
  - "Staphylococcus aureus"

ignored_substrings:
  - "(organism)"
  - "(sugarcane)"
  - "(cow)"
  - "(orangutan)"
  - "(leopard)"
  - ", juvenile"
  - ", adult"
  - "(undetermined species)"
  - "[NCBITaxon:9913]"
  - "[NCBITaxon:9031]"
  - "[NCBITaxon:9825]"
  - "[GENEPIO:0001619]"
  - "(Saba)"
  - "(turkey)"
  - "(goose)"
  - "(Broiler)"
  - "(not applicable)"
  - ".cf"
  - "sp."
  - "spp."
  - "imported"
  - "Free range"
  - "(wild living)"
  - "parent"
  - "(variety unknown)"
  - "(cougar)"
  - "(lion)"
  - "(domestic cat)"
  - "(Bovine species animal)"
  - "(cattle)"
  - "(pig)"
  - "(gull)"
  - "wild field collected strain"
  - "wild"
  - "moribund"
  - "infected"
  - "healthy"
  - "L."
  - "(bird)"
  - "(goat)"
  - "host"
  - "Farmed"
  - "lactating"

iso_keywords:
  - "food"
  - "meat"
  - "environment"
  - "soil"

overrides:
  # null = reject
  taxid_overrides:
    "Squirrel monkey": 9520         # Saimiri genus
    "cattle or sheep": 27592        # Bovinae
    "colon": null
    "dialysis": null
    "cancer": null
    "bronchus": null
    "bovine-swine pool": null          # Should be environmental instead?
    "Lama glama and Vicugna pacos": null
    "Milvus lineatus lineatus": 52810 # Milvus migrans
    "animal and human": 33208         # Metazoa
    "poultry flies": 7147
