ignored_substrings:
  - "(organism)"
  - "(sugarcane)"
  - "(cow)"
  - "(orangutan)"
  - "(leopard)"
  - ", juvenile"
  - ", adult"
  - "(undetermined species)"
  - "[NCBITaxon:9913]"
  - "[NCBITaxon:9031]"
  - "[NCBITaxon:9825]"
  - "[GENEPIO:0001619]"
  - "(Saba)"
  - "(turkey)"
  - "(goose)"
  - "(Broiler)"
  - "(not applicable)"
  - ".cf"
  - "sp."
  - "spp."
  - "imported"
  - "Free range"
  - "(wild living)"
  - "parent"
  - "(variety unknown)"
  - "(cougar)"
  - "(lion)"
  - "(domestic cat)"
  - "(Bovine species animal)"
  - "(cattle)"
  - "(pig)"
  - "(gull)"
  - "wild field collected strain"
  - "wild"
  - "moribund"
  - "infected"
  - "healthy"
  - "L."
  - "(bird)"
  - "(goat)"
  - "host"
  - "Farmed"
  - "lactating"

iso_keywords:
  - "food"
  - "meat"
  - "beef"
  - "veal"
  - "pork"
  - "environment"
  - "soil"

overrides:
  # null = reject
  taxid_overrides:
    "Squirrel monkey": 9520         # Saimiri genus
    "cattle or sheep": 27592        # Bovinae
    "colon": null
    "dialysis": null
    "cancer": null
    "bronchus": null
    "bovine-swine pool": null
    "Lama glama and Vicugna pacos": null
    "Milvus lineatus lineatus": 52810 # Milvus migrans
    "animal and human": 33208         # Metazoa
    "poultry flies": 7147
